# trigger:
#   branches:
#     include:
#       - hlog

trigger: none

name: $(date:yyyyMMdd)$(rev:.r)

variables:
  - group: HLOG-ENV-BACKEND
  - name: GIT_BRANCH
    value: $(Build.SourceBranchName)
  - name: GIT_COMMIT
    value: $(Build.SourceVersion)
  - name: IS_HLOG
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/hlog')]

pool:
  name: AZURE-DEVOPS-SERPRO-$(GIT_BRANCH)

stages:
  - stage: BuildAPP
    jobs:
      - job: Job_2
        displayName: Build da Aplicação
        steps:
          - task: CopyFiles@2
            displayName: Copia dos Arquivos
            inputs:
              SourceFolder: './'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              OverWrite: true
          - task: PublishBuildArtifacts@1
            displayName: Publicando os Arquivos
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  - stage: DeployToHLOG
    jobs:
      - job: Job_3
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/hlog')
        displayName: Deploy em Homologação
        variables:
          - group: HLOG-APP-BACKEND
        steps:
          - task: AWSShellScript@1
            displayName: Login Registry AWS
            inputs:
              regionName: 'sa-east-1'
              scriptType: 'inline'
              inlineScript: |
                echo "Logging in to AWS ECR"
                aws --version
                aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin $(aws_ecr_registry)
          - task: AWSShellScript@1
            displayName: Substituído as variáveis de ambiente
            inputs:
              regionName: 'sa-east-1'
              scriptType: 'inline'
              inlineScript: |
                echo "Substituído as variáveis de ambiente"
                printenv | grep API_ | sed "s/API_//" | awk -F= '{ print "{ \"name\":" "\""$1"\", \"value\":" "\""$2"\" }"  }' > env.json
                jq -s '.' env.json > input.json
          - task: AWSShellScript@1
            displayName: Substituído as variáveis de segurança
            inputs:
              regionName: 'sa-east-1'
              scriptType: 'inline'
              inlineScript: |
                echo "Substituído as variáveis de segurança"
                printenv | grep SEC_ | sed "s/SEC_//" | awk -F= '{ print "{ \"name\":" "\""$1"\", \"valueFrom\":" "\""$2"\" }"  }' > secret.json
                jq -s '.' secret.json > input-secret.json
          - task: Docker@2
            displayName: Build e Push da Imagem
            inputs:
              repository: '$(aws_ecr_registry)/$(aws_ecr_repository)'
              command: 'buildAndPush'
              Dockerfile: './Dockerfile-backend'
              tags: |
                $(GIT_COMMIT)-$(Build.BuildId)
          - task: AWSShellScript@1
            displayName: Updating task definition
            inputs:
              regionName: 'sa-east-1'
              scriptType: 'inline'
              inlineScript: |
                cat input.json
                echo "Obtendo a definição de task atual..."
                aws ecs describe-task-definition --task-definition $(aws_ecs_task) > task-def.json
                cat task-def.json
                NEW_IMAGE="$(aws_ecr_registry)/$(aws_ecr_repository):$(GIT_COMMIT)-$(Build.BuildId)"
                echo "Criando nova definição de task com a nova imagem ($NEW_IMAGE)..."
                NEW_TASK_DEF=$(jq --arg IMAGE "$NEW_IMAGE" --slurpfile APPENV input.json --slurpfile APPSECRET input-secret.json '.taskDefinition | {containerDefinitions, volumes, family, taskRoleArn, executionRoleArn, networkMode, requiresCompatibilities, cpu, memory} | .containerDefinitions[0].image = $IMAGE | .containerDefinitions[0].environment = $APPENV[0] | .containerDefinitions[0].secrets = $APPSECRET[0]' task-def.json)                
                echo "$NEW_TASK_DEF" > new-task-def.json
                cat new-task-def.json
                echo "Registrando a nova definição de task..."
                TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json | jq -r '.taskDefinition.taskDefinitionArn')
                echo "Atualizando o serviço ECS com a nova task definition"
                aws ecs update-service --cluster $(aws_ecs_cluster) --service $(aws_ecs_service) --task-definition $TASK_DEF_ARN
  - stage: CleanUp
    condition: succeededOrFailed()
    jobs:
      - job: Job_4
        displayName: Limpando arquivos
        steps:
          - task: Bash@3
            displayName: Removing docker images
            inputs:
              targetType: 'inline'
              script: |
                docker system prune --all --force