sonar.projectKey=nvsl-frontend
sonar.projectName=NVSL Frontend
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

# Coverage LCOV gerado pelo Vitest (@vitest/coverage-v8)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.qualitygate.wait=true
