sonar.projectKey=nvsl-backend
sonar.projectName=NVSL Backend
sonar.projectVersion=1.0.0

sonar.sources=app,routes
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/vendor/**,**/*.min.js,**/node_modules/**

# PHP coverage report gerado pelo phpunit
sonar.php.coverage.reportPaths=coverage.xml

# Análise de qualidade
sonar.qualitygate.wait=true
sonar.php.version=8.4
